spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_runner?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: dev # 激活 dev 环境
mybatis:
  type-aliases-package: com.haiyang.campusrunner.pojo
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /